Nix flake
Pumpkin-MC/Pumpkin pull request #283
Opened 2024-11-15 10:13 UTC by nicholaschiasson

## Description

* Adding initial nix flake capable of building the code
* Checking Cargo.lock into version control

## Testing

N/A since there is no code change.

I simply ran `nix run` locally to test that it is working.

## Checklist
Things need to be done before this Pull Request can be merged.

- [ ] Review if we want to expand upon dev shell, adding extra tooling for local devel/opment for those who wish to use nix
- [ ] Review pinned SHA for fastnbt dependency and if this is necessary (not preferred since there is a manual step introduced in updating the flake in case we ever want to upgrade this dependency).
- [ ] Review version in buildRustPackage, which is currently simply pulled from `./pumpkin/Cargo.toml`. This is probably fine, except that it could be misleading about the outputs being built, masquerading the output as a proper release, when the build is coming from a feature branch. Maybe better would be to derive version somehow from git ref at HEAD or something.

2024-11-16 01:16 UTC, nicholaschiasson commented
For fastnbt dep, I understand now the reason it is necessary to pin the SHA in this flake is because the dependency is specified in a few `Cargo.toml`s using a git url. Is this because we need features not yet available in an official release (2.5.0), that are only in fastnbt master branch? And as a side question, is this a blocker before pumpkin itself can also have a stable release?

With this change, I have checked the Cargo.lock into version control, since that is the recommendation for rust projects that output binaries. The flake itself depends on the lock file as well, so it kind of makes the Cargo.lock file necessary. If that is problematic, then this change may be inappropriate for this repo. However, I think it will also help here. And for new contributors as well, since we guarantee people are getting the same versions of dependencies after a fresh repo clone.

If we ever wish to update the fastnbt dependency, the flake file will need to be updated too to reflect the new hash (tedious), or if we can pin against a new fastnbt release from the crates registry, we can remove the explicit pinning from the flake. That would be best because then there would be no hard coded versions in there and the file would rarely/never require further modification.

2024-11-16 12:13 UTC, Snowiiii commented
We are currently moving to an own NBT Crate. Should be done soon. Only some issues with arrays when deserializing.
https://github.com/Snowiiii/Pumpkin/pull/100

2024-11-26 07:28 UTC, Snowiiii commented
I decided to partially move to our own NBT crate due to a Problem with Deserialization when having Arrays. Until the Problem is not solved we still need to use fastnbt for reading anvil chunks

2024-12-14 01:47 UTC, IogaMaster commented
I +1 this

2025-02-02 07:28 UTC, Eveeifyeve commented
This shell could be cleaned up by using 

flake.nix
```nix
{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-parts.url = "github:hercules-ci/flake-parts";
    flake-compat.url = "https://flakehub.com/f/edolstra/flake-compat/1.tar.gz";
    rust-overlay = {
      url = "github:oxalica/rust-overlay";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = inputs@{ nixpkgs, flake-parts, ... }:
    flake-parts.lib.mkFlake {inherit inputs;} {
      systems = nixpkgs.lib.systems.flakeExposed;
      perSystem = {
        lib,
        pkgs,
        system,
        config,
        ...
      }: 
      {
        _module.args.pkgs = import nixpkgs {
          inherit system;
          overlays = [
            (import inputs.rust-overlay)
          ];
        };

        devShells.default = with pkgs; let 
        toolchain =  break ((pkgs.rust-bin.fromRustupToolchainFile ./rust-toolchain.toml).override {
          extensions = [ "rust-analyzer" "rust-src" ];
          targets = ["x86_64-unknown-linux-gnu"];
        }); 
        in mkShell
        {
          nativeBuildInputs = with pkgs; [
            toolchain
            openssl
            pkgs-config
          ] ++ lib.optionals stdenv.isDarwin [
            apple-sdk
          ];
        };
      };
    };
}
```

shell.nix (for non flakes)
```nix
(import
  (
    let
      lock = builtins.fromJSON (builtins.readFile ./flake.lock);
      nodeName = lock.nodes.root.inputs.flake-compat;
    in
    fetchTarball {
      url = lock.nodes.${nodeName}.locked.url or "https://github.com/edolstra/flake-compat/archive/${lock.nodes.${nodeName}.locked.rev}.tar.gz";
      sha256 = lock.nodes.${nodeName}.locked.narHash;
    }
  )
  { src = ./.; }
).shellNIx
```

2025-02-02 09:13 UTC, nicholaschiasson commented
> This shell could be cleaned up by not repackaging pumpkin instead letting the user build it themselves and utilising the `rust-toolchain.toml`.

This flake is not only a dev shell. I'm using the package feature of flakes to support using nix as the build system for those who desire it. This way, this repo could be pointed to as a flake package from other flakes or simply built with `nix build`, built and run with `nix run`, etc. Sorry, but I disagree with removing that configuration the way you suggest.

Also, my flake is already using `rust-toolchain.toml`. Maybe you just overlooked it?

shell.nix is a welcome addition though, I can add that later when I have some time.

2025-02-02 09:42 UTC, Eveeifyeve commented
> > This shell could be cleaned up by not repackaging pumpkin instead letting the user build it themselves and utilising the `rust-toolchain.toml`.
> 
> This flake is not only a dev shell. I'm using the package feature of flakes to support using nix as the build system for those who desire it. This way, this repo could be pointed to as a flake package from other flakes or simply built with `nix build`, built and run with `nix run`, etc. Sorry, but I disagree with removing that configuration the way you suggest.

I feel like the package should be located at nixpkgs instead of here it doesn't make sense to build a package here, as when your cloning this repo you want to develop pumpkin not coming here to package pumpkin when that could be done in the nixpkgs side I disagree there shouldn't be a package in this repo when the package could be located at nixpkgs and you just use include it in the devshell here but if you want to build your local changes it should be a simple `cargo build --release` then `cargo run --release` to test your changes.

> Also, my flake is already using `rust-toolchain.toml`. Maybe you just overlooked it?
Yes but it doesn’t override what you only need if there is a change that is made to the `rust-toolchain.toml` you wouldn’t need unnecessary dependencies.

2025-02-02 12:45 UTC, nicholaschiasson commented
I agree nixpkgs should distribute the package. Obviously that depends on achieving a stable release at some point, so it cannot be worked on just yet anyway. But can you explain the harm in defining a flake package as well? That's arguably the core feature and incentive of using nix flakes. It's not just for defining a dev shell.

2025-02-02 15:07 UTC, Eveeifyeve commented
> I agree nixpkgs should distribute the package. Obviously that depends on achieving a stable release at some point, so it cannot be worked on just yet anyway. But can you explain the harm in defining a flake package as well? That's arguably the core feature and incentive of using nix flakes. It's not just for defining a dev shell.

I mean your just repeating yourself there is no harm.

2025-02-02 15:43 UTC, DataM0del requested changes
Remove cargo.lock :vomiting_face:

2025-02-02 16:12 UTC, Eveeifyeve commented on flake.lock
It used for versioning the dependancies in the flake you can't get rid of this.

2025-02-02 16:13 UTC, Eveeifyeve commented on .gitignore
> +# Cargo.lock
No it's useful for ci/cd and package managers cargo lock is generally considered now to be included.

2025-02-02 16:13 UTC, Eveeifyeve commented on .gitignore
> +# Cargo.lock
Please read https://doc.rust-lang.org/cargo/faq.html#why-have-cargolock-in-version-control

2025-02-02 16:17 UTC, Eveeifyeve commented
Not to be rude or anything @DataM0del, I don't think you have done research before making the review comments above this comment, before making a review comment could you please dedicate your time to do some research, please and thanks.

2025-02-02 18:41 UTC, DataM0del commented on flake.lock
usually lock files describe hashes of the dependencies and not versions, that's weird.

2025-02-02 18:43 UTC, DataM0del commented on .gitignore
> +# Cargo.lock
In my opinion, the 3 use cases for lock files are almost never happen since no one usually force pushes a update with breaking changes to the API, but it also can add merge conflicts. I generally keep Cargo.lock ignored since I don't find it useful.

2025-02-02 20:12 UTC, nicholaschiasson commented on .gitignore
> +# Cargo.lock
Agreeing with @Eveeifyeve . I will not apply this suggestion. Just about every rust project, especially those outputting a binary application, should include cargo.lock. If maintainers choose not to accept my change because of that, that's fine with me.

2025-02-02 20:13 UTC, nicholaschiasson commented on flake.lock
"That's weird?" ...🤔

2025-02-03 00:58 UTC, DataM0del commented on flake.lock
> "That's weird?" ...🤔

I meant unusual.

2025-02-03 16:50 UTC, Eveeifyeve commented on flake.lock
It was just how it was [implemented in the 49 rfc](https://github.com/tweag/rfcs/blob/ca2845b81814c345945de4be0b36cd5fb4eb080b/rfcs/0049-flakes.md?plain=1#L266) you can also [read more about flakes here](https://nix.dev/concepts/flakes.html#flakes)

2025-02-16 12:40 UTC, Snowiiii commented
@nicholaschiasson Fastnbt is finally gone with the latest commit :rocket:

2025-02-27 15:03 UTC, Snowiiii commented
@nicholaschiasson do you still plan to work on this ?

2025-02-27 18:04 UTC, Eveeifyeve commented
> @nicholaschiasson do you still plan to work on this ?

I will wait at least a month or two before I take over.

2025-03-02 14:06 UTC, Snowiiii commented
Feel free to reopen

2025-03-02 14:06 UTC, closed without merging

2025-03-03 10:18 UTC, nicholaschiasson commented
Hey guys, sorry, I was on vacation. I am okay with @Eveeifyeve taking over maintaining nix and nix flake support. 👍

2025-03-05 03:40 UTC, Eveeifyeve commented
I will submit a pr later today that will be a better version of this pr using flake-parts having support for flake-compact and outright making the package using fetchvendoring readmore about it here:  https://nixos.org/manual/nixpkgs/stable/#compiling-rust-applications-with-cargo